"""
demo_mission_briefing.py
========================
Planet Express Mission Briefing — LLM workflow demo.

Illustrates the template + content injection pattern:
  1. Define a formatting template (structure, colors, positions)
  2. Simulate LLM output (title, briefing text, mission rows)
  3. Inject content into a deep copy of the template
  4. Call build_presentation()

Run:
    python3 demo_mission_briefing.py
"""

from copy import deepcopy
from datetime import datetime, timezone

from pptx_functions import build_presentation

# ── Step 1: Template ─────────────────────────────────────────────────────────
# All formatting is fixed here.  Content fields (marked with comments) are
# intentionally empty — the LLM fills them in Step 2.

template = {
    "Details": {
        "Author":               "B. Rodriguez",
        "Title":                "Planet Express Mission Briefing",
        "Subject":              "pptx_functions Workflow Demo",
        "Comments":             "Generated programmatically using pptx_functions",
        "Keywords":             "pptx, futurama, mission briefing",
        "Category":             "Workflow Automation",
        "Filename":             "DEMO - Mission Briefing (%s).pptx",
        "Slide Aspect Ratio":   "16:9",
        "Slide Width & Height": [13.33, 7.5],
    },
    "Slides": {
        "Slide 01": {
            "Slide Template":   6,
            "Slide Name":       "Mission Briefing",
            "Slide Notes":      "Auto-generated by pptx_functions.",
            "Background Color": "#0d1b2a",
            "Background Alpha": 0.0,
            "Objects": {

                # ── Banners ──────────────────────────────────────────────────
                "Banner": {
                    "Add?":        True,
                    "Object Type": "Banner",
                    "Text":        "PLANET EXPRESS — FOR EXTERNAL USE ONLY",
                    "Font Color":  "#ffffff",
                    "Font Size":   14,
                    "Bold?":       True,
                    "Fill Color":  "#6a0572",
                },

                # ── Planet Express logo ───────────────────────────────────
                "Logo": {
                    "Add?":                   True,
                    "Object Type":            "Image",
                    "img_path":               "img/Futurama_Planet_Express.png",
                    "Preserve Aspect Ratio?": True,
                    "fit":                    "height",
                    "left": 0.169, "top": 0.1464, "width": 1.14, "height": 1.05,
                },

                # ── Slide title ───────────────────────────────────────────
                "Title": {
                    "Add?":        True,
                    "Object Type": "Text",
                    "Text":        "",          # ← LLM fills this
                    "left": 1.4149, "top": 0.4214, "width": 10.5, "height": 0.5,
                    "Align":       "center",
                    "V Align":     "middle",
                    "Font Name":   "Calibri",
                    "Font Size":   28,
                    "Font Color":  "#f5c518",
                    "Bold?":       False,
                    "Italic?":     False,
                    "Word Wrap?":  True,
                    "Fill Color":  None,
                    "Fill Alpha":  1.0,
                    "Line Color":  None,
                    "Line Width":  0,
                    "Line Style":  "-",
                },

                # ── Mission log table ─────────────────────────────────────
                "Mission Log": {
                    "Add?":           True,
                    "Object Type":    "Table",
                    "left": 1.5149, "top": 1.0893, "width": 10.3, "height": 1.6,
                    "Columns":        4,
                    "Rows":           0,            # ← updated after LLM fills rows
                    "Column Widths":  [2.8, 1.4, 4.3, 1.8],
                    "Row Height":     0.4,
                    "Column Headers": ["Destination", "Date", "Cargo Manifest", "Danger Level"],
                    "Row Data":       [],           # ← LLM fills this
                    "Font Name":      "Calibri",
                    "Font Size":      14,
                    "Font Color":     "#333333",
                    "Align":          "center",
                    "V-Align":        "middle",
                    "Bold?":          True,
                    "Cell Styles": {
                        # Header row: blue background + white text
                        (0, 0): {"Font Color": "#ffffff", "Fill Color": "#5b7fae"},
                        (0, 1): {"Font Color": "#ffffff", "Fill Color": "#5b7fae"},
                        (0, 2): {"Font Color": "#ffffff", "Fill Color": "#5b7fae"},
                        (0, 3): {"Font Color": "#f5c518", "Fill Color": "#0d1b2a"},
                    },
                },

                # ── Speech bubble (Oval Callout autoshape) ────────────────
                "Speech Bubble": {
                    "Add?":          True,
                    "Object Type":   "AutoShape",
                    "AutoShape Key": "oval callout",
                    "Text":          "",            # ← LLM fills this
                    "left": 2.0071, "top": 2.7321, "width": 5.4857, "height": 1.3,
                    "Align":         "center",
                    "V Align":       "middle",
                    "Font Name":     "Chalkboard",
                    "Font Size":     10,
                    "Font Color":    "#1a1a2e",
                    "Bold?":         False,
                    "Italic?":       False,
                    "Word Wrap?":    True,
                    "Fill Color":    "#b3d7f5",
                    "Fill Alpha":    1.0,
                    "Line Color":    "#5b7fae",
                    "Line Width":    1.5,
                    "Line Style":    "-",
                },

                # ── Professor Farnsworth (bottom-left) ────────────────────
                "Farnsworth": {
                    "Add?":                   True,
                    "Object Type":            "Image",
                    "img_path":               "img/ProfessorFarnsworth.png",
                    "Preserve Aspect Ratio?": True,
                    "fit":                    "height",
                    "left": 0.3208, "top": 3.3071, "width": 2.19, "height": 3.6,
                },

                # ── Bender (bottom-right) ─────────────────────────────────
                "Bender": {
                    "Add?":                   True,
                    "Object Type":            "Image",
                    "img_path":               "img/Bender_Rodriguez.png",
                    "Preserve Aspect Ratio?": True,
                    "fit":                    "height",
                    "left": 10.3485, "top": 3.3071, "width": 2.48, "height": 3.6,
                },

            },
        },
    },
}

# ── Step 2: Simulated LLM output ─────────────────────────────────────────────
# In production this dict comes from an LLM API call.
# The LLM only knows about these three fields — no python-pptx, no coordinates.

llm_output = {
    "title":    "Planet Express Weekly Mission Briefing — Stardate 29 APR 3000",
    "briefing": (
        "Good news, Everyone!  I've assigned you three new deliveries to "
        "destinations that will, in all likelihood, result in at least one of "
        "your deaths.  The good news is I have no strong attachment to any of "
        "you.  Now stop touching my things."
    ),
    "rows": [
        ["Omicron Persei 8",  "29 APR 3000", "1 can of anchovies (urgent)",       "High"],
        ["Robot Hell",        "30 APR 3000", "Bender's soul (retrieve, again)",   "Medium"],
        ["Planet Nude Beach", "01 MAY 3000", "Swimsuit calendars — rush order", "Low"],
    ],
}

# ── Step 3: Inject content into a copy of the template ───────────────────────

slide_config = deepcopy(template)
objs = slide_config["Slides"]["Slide 01"]["Objects"]

objs["Title"]["Text"]              = llm_output["title"]
objs["Speech Bubble"]["Text"]      = llm_output["briefing"]
objs["Mission Log"]["Row Data"]    = llm_output["rows"]
objs["Mission Log"]["Rows"]        = len(llm_output["rows"])

# Alternating row background colours
row_fills = ["#e8edf5", "#f5f7fa"]
for i in range(1, len(llm_output["rows"]) + 1):
    fill = row_fills[(i - 1) % 2]
    for j in range(4):
        cs = objs["Mission Log"]["Cell Styles"]
        cs[(i, j)] = {**cs.get((i, j), {}), "Fill Color": fill}

# Danger Level column: colour-coded font
danger_colors = {"High": "#cb181d", "Medium": "#e6a817", "Low": "#007a33"}
for i, row in enumerate(llm_output["rows"], start=1):
    cs = objs["Mission Log"]["Cell Styles"]
    cs[(i, 3)] = {**cs.get((i, 3), {}),
                  "Font Color": danger_colors.get(row[3], "#535353"),
                  "Bold?": True}

# ── Step 4: Build ─────────────────────────────────────────────────────────────

created = datetime.now(timezone.utc).strftime("%Y-%m-%d %H%MZ")
slide_config["Details"]["Filename"] = (
    slide_config["Details"]["Filename"] % created
)

prs = build_presentation(slide_config, verbose=True)
prs.save(slide_config["Details"]["Filename"])
print(f"Saved: {slide_config['Details']['Filename']}")
